window.PROFILE_LOCALES = window.PROFILE_LOCALES || {};
window.PROFILE_LOCALES.en = {
  pageTitle: "Blueprints code compression",
  appTitle: "FCT BLUEPRINTS CODE COMPRESSION",
  optimizerTitle: "Blueprint optimizer for Factorio",
  optimizerDesc: "Compress blueprints to save space and optimize Steam guides",
  frameTitle: "BLUEPRINT COMPRESSOR",
  originalTitle: "ORIGINAL BLUEPRINT",
  compressedTitle: "COMPRESSED BLUEPRINT",
  originalPlaceholder: "Paste blueprint string here...",
  compressButton: "COMPRESS BLUEPRINT",
  clearButton: "CLEAR",
  compressedPlaceholder: "Compressed blueprint code will appear here...",
  copyButton: "COPY",
  verifyButton: "VERIFY",
  tipsTitle: "Notes:",
  tip1: "Create a backup before use",
  tip2: "Optimization works best for large blueprints",
  tip3: "Very old or very new versions may have compatibility issues",
  createdWith: "Created with support from the FCTostin Telegram community",
  statusEmptyBlueprint: "ERROR: Paste blueprint code first!",
  statusInvalidBlueprint: "ERROR: Invalid format. Blueprint code must start with \"0\"",
  statusCompressed: "Blueprint compressed and optimized successfully!",
  statusNoCompressed: "ERROR: There is no compressed blueprint to verify!",
  statusVerified: "Verification successful. Blueprint is valid.",
  statusVerifyError: "ERROR while verifying: ",
  statusCompressError: "ERROR: ",
  statusCopied: "Blueprint copied to clipboard!",
  statsLabel: "STATS"
};
