window.PROFILE_LOCALES = window.PROFILE_LOCALES || {};
window.PROFILE_LOCALES.ru = {
  pageTitle: "Blueprints code compression",
  appTitle: "FCT BLUEPRINTS CODE COMPRESSION",
  optimizerTitle: "Оптимизатор чертежей для Factorio",
  optimizerDesc: "Сжимайте чертежи для экономии места и оптимизации руководств Steam",
  frameTitle: "КОМПРЕССОР ЧЕРТЕЖЕЙ",
  originalTitle: "ОРИГИНАЛЬНЫЙ ЧЕРТЕЖ",
  compressedTitle: "СЖАТЫЙ ЧЕРТЕЖ",
  originalPlaceholder: "Вставьте строку чертежа здесь...",
  compressButton: "СЖАТЬ ЧЕРТЕЖ",
  clearButton: "ОЧИСТИТЬ",
  compressedPlaceholder: "Здесь появится сжатый код чертежа...",
  copyButton: "СКОПИРОВАТЬ",
  verifyButton: "ПРОВЕРИТЬ",
  tipsTitle: "Примечания:",
  tip1: "Делайте резервную копию перед использованием",
  tip2: "Оптимизация работает лучше всего для больших чертежей",
  tip3: "Могут быть проблемы совместимости с очень старыми или новыми версиями",
  createdWith: "Создано при поддержке Телеграм сообщества FCTostin",
  statusEmptyBlueprint: "ОШИБКА: Вставьте код чертежа!",
  statusInvalidBlueprint: "ОШИБКА: Неверный формат чертежа. Код должен начинаться с \"0\"",
  statusCompressed: "Чертеж успешно сжат и оптимизирован!",
  statusNoCompressed: "ОШИБКА: Нет сжатого чертежа для проверки!",
  statusVerified: "Проверка успешна! Чертеж работоспособен.",
  statusVerifyError: "ОШИБКА при проверке: ",
  statusCompressError: "ОШИБКА: ",
  statusCopied: "Чертеж скопирован в буфер обмена!",
  statsLabel: "СТАТИСТИКА"
};
